[package]
name = "stock_spreadsheet_generator"
description = "Creates a simple spreadsheet based on yahoo finance data"
version = "0.5.1"
authors = ["marcus8448"]
edition = "2021"
readme = "README.md"
repository = "https://github.com/marcus8448/stock_spreadsheet_generator/"
license = "MIT"

[dependencies]
async-compat = "0.2.1"
chrono = "0.4"
clap = "3.1"
csv = "1.1"
futures = "0.3"
open = "2.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.5"
reqwest = { version = "0.11", features = ["json"] }

[target.'cfg(windows)'.build-dependencies]
winres = { version = "0.1" }