[package]
name = "stock_spreadsheet_generator"
description = "Creates a simple spreadsheet based on yahoo finance data"
version = "0.4.0"
authors = ["marcus8448"]
edition = "2021"
readme = "README.md"
repository = "https://github.com/marcus8448/stock_spreadsheet_generator/"
license = "MIT"

[dependencies]
chrono = "0.4"
clap = "3.1"
csv = "1.1"
futures = "0.3"
open = "2.1"
serde = "1.0"
toml = "0.5"
yahoo_finance_api = "1.2.2"
